name: NAIS Alerts Deploy

on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
        description: NAIS cluster to deploy to
      resource:
        required: true
        type: string
        description: NAIS resource to use for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: Deploy to Environment
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: ${{ inputs.resource }}
          TIMEOUT: 10m
          PRINT_PAYLOAD: true
