name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        description: Node version to build with
        default: '22'
      pnpm-version:
        required: false
        type: string
        description: pnpm version to build with
        default: '9'

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: ${{ inputs.pnpm-version }}
          run_install: false
      - id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('server/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies for client
        run: pnpm install

      - name: Install dependencies for server
        run: cd server && pnpm install

      - name: Build server
        run: cd server && pnpm run build

      - name: Build app
        run: pnpm run build
